// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4Tg5z0ZQ3_jPaSUG2Fk2jBzjAvAOi24',
    appId: '1:570905742340:web:e60c733fef8ec89247f951',
    messagingSenderId: '570905742340',
    projectId: 'flipkartclone-de681',
    authDomain: 'flipkartclone-de681.firebaseapp.com',
    storageBucket: 'flipkartclone-de681.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsdp70_PxvwCRFTbiBRUQ3TZWorMLQgCY',
    appId: '1:570905742340:android:f52301e19a22232c47f951',
    messagingSenderId: '570905742340',
    projectId: 'flipkartclone-de681',
    storageBucket: 'flipkartclone-de681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPRLFdWWkQZH91WTVer7SbFhuWbCJ9aAM',
    appId: '1:570905742340:ios:99497be23b5e967047f951',
    messagingSenderId: '570905742340',
    projectId: 'flipkartclone-de681',
    storageBucket: 'flipkartclone-de681.appspot.com',
    iosClientId: '570905742340-mem8i3r8nv5i8p94i5ial3a2gn1gv12p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPRLFdWWkQZH91WTVer7SbFhuWbCJ9aAM',
    appId: '1:570905742340:ios:99497be23b5e967047f951',
    messagingSenderId: '570905742340',
    projectId: 'flipkartclone-de681',
    storageBucket: 'flipkartclone-de681.appspot.com',
    iosClientId: '570905742340-mem8i3r8nv5i8p94i5ial3a2gn1gv12p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartclone',
  );
}
